# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-25 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180223_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='missed_count',
            field=models.IntegerField(default=0),
        ),
    ]
