# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_userinfo_missed_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='start_date',
            field=models.DateField(),
        ),
    ]
