# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-26 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180225_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='per_dur',
            field=models.IntegerField(default=0),
        ),
    ]
