# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180226_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.TextField(max_length=2000)),
                ('ans', models.TextField(max_length=2000)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserInfo')),
            ],
        ),
    ]
