# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-01 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_auto_20180301_0056'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=2000)),
                ('answ', models.CharField(max_length=2000)),
            ],
        ),
    ]
